RN50:
    embed_dim: 1024
    image_resolution: 224
    vision_layers: [3, 4, 6, 3]
    vision_width: 256
    vision_patch_size: 0
    context_length: 77
    vocab_size: 49408
    transformer_width: 512
    transformer_heads: 8
    transformer_layers: 12


RN101:
    embed_dim: 512
    image_resolution: 224
    vision_layers: [3, 4, 23, 3]
    vision_width: 256
    vision_patch_size: 0
    context_length: 77
    vocab_size: 49408
    transformer_width: 512
    transformer_heads: 8
    transformer_layers: 12


RN50x4:
    embed_dim: 640
    image_resolution: 288
    vision_layers: [4, 6, 10, 6]
    vision_width: 320
    vision_patch_size: 0
    context_length: 77
    vocab_size: 49408
    transformer_width: 640
    transformer_heads: 10
    transformer_layers: 12


RN50x16:
    embed_dim: 768
    image_resolution: 384
    vision_layers: [6, 8, 18, 8]
    vision_width: 384
    vision_patch_size: 0
    context_length: 77
    vocab_size: 49408
    transformer_width: 768
    transformer_heads: 12
    transformer_layers: 12

RN50x64:
    embed_dim: 1024
    image_resolution: 448
    vision_layers: [3, 15, 36, 10]
    vision_width: 512
    vision_patch_size: 0
    context_length: 77
    vocab_size: 49408
    transformer_width: 1024
    transformer_heads: 16
    transformer_layers: 12