ViT-B/32:
    embed_dim: 512
    image_resolution: 224
    vision_layers: 12
    vision_width: 768
    vision_patch_size: 32
    context_length: 77
    vocab_size: 49408
    transformer_width: 512
    transformer_heads: 8
    transformer_layers: 12

ViT-B/16:
    embed_dim: 512
    image_resolution: 224
    vision_layers: 12
    vision_width: 768
    vision_patch_size: 16
    context_length: 77
    vocab_size: 49408
    transformer_width: 512
    transformer_heads: 8
    transformer_layers: 12

ViT-L/14:
    embed_dim: 768
    image_resolution: 224
    vision_layers: 24
    vision_width: 1024
    vision_patch_size: 14
    context_length: 77
    vocab_size: 49408
    transformer_width: 768
    transformer_heads: 12
    transformer_layers: 12

ViT-L/14-336px:
    embed_dim: 768
    image_resolution: 336
    vision_layers: 24
    vision_width: 1024
    vision_patch_size: 14
    context_length: 77
    vocab_size: 49408
    transformer_width: 768
    transformer_heads: 12
    transformer_layers: 12
